### ISSUE TITLE
Web UI (Beta) RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by bycloudai** [RameenAbdal/StyleFlow#50]
Hi, thank you for your amazing work!

I've tried to run the Web UI on my own PC, but it seems that I've encountered this error:
![Screenshot 2021-01-27 094656](https://user-images.githubusercontent.com/29135514/105930596-d88cfc80-6084-11eb-970e-2b7c659fbba9.png)
is there any work around for CUDA out of memory?

This is my GPU usage btw when running the Streamlit:
![Screenshot 2021-01-27 094918](https://user-images.githubusercontent.com/29135514/105930702-f5c1cb00-6084-11eb-86b8-249068a1d329.png)

Thank you!

**Comment by philipmiesbauer** [comment]
Same here

**Comment by sbushmanov** [comment]
Same here.

What are your GPU specs? They seem to [require](https://github.com/NVlabs/stylegan2) 16Gb+ GPU, though it's not clear if it applies to training or predicting as well.
Were you able to get "normal" ui working?

**Comment by philipmiesbauer** [comment]
I work through with SSH on a remote machine without screen, so "normal" UI
isn't an option and X11 forwarding doesn't seem to work.

I don't have 16GB though

**Comment by sbushmanov** [comment]
Change in `app.py` around line 94:

```
@st.cache(hash_funcs=HASH_FUNCS)
def init_model():
    # Open a new TensorFlow session.
    config = tf.ConfigProto(allow_soft_placement=True)
    session = tf.Session(config=config)
```

to:

```
@st.cache(hash_funcs=HASH_FUNCS)
def init_model():
    # Open a new TensorFlow session.
    #config = tf.ConfigProto(allow_soft_placement=True)
    #session = tf.Session(config=config)
    config = tf.ConfigProto()
    config.gpu_options.allow_growth=True
    session = tf.Session(config=config)
```
and you're good to go.

**Comment by philipmiesbauer** [comment]
Thanks. Worked like a charm. Brilliant.
