### ISSUE TITLE
SyleFlow WebUI - failed to initialize

### ISSUE THREAD

**Issue by ronybot** [RameenAbdal/StyleFlow#94]
Hi,
I running  streamlit run app.py on the WebUI branch on AWS p3.16xlarge server with the following setup 
GPU 8, 
GPU peer to Peer NVLink 
GPU memory (GB) 128
vCPU 64
Memory (GP) 488
Cuda compilation tools, release 10.0, V10.0.130

getting the error   RuntimeError: CUDA error: out of memory

File "/home/ubuntu/.local/lib/python3.6/site-packages/streamlit/script_runner.py", line 338, in _run_script
    exec(code, module.__dict__)
File "/home/ubuntu/src/StyleFlow/webui/app.py", line 312, in <module>
    main()
File "/home/ubuntu/src/StyleFlow/webui/app.py", line 219, in main
    session, model, w_avg, flow_model = init_model()
File "/home/ubuntu/.local/lib/python3.6/site-packages/streamlit/caching.py", line 573, in wrapped_func
    return get_or_create_cached_value()
File "/home/ubuntu/.local/lib/python3.6/site-packages/streamlit/caching.py", line 557, in get_or_create_cached_value
    return_value = func(*args, **kwargs)
File "/home/ubuntu/src/StyleFlow/webui/app.py", line 104, in init_model
    prior = cnf(512, '512-512-512-512-512', 17, 1)
File "../module/flow.py", line 79, in cnf
    model = build_model(input_dim, dims, zdim, num_blocks, True).cuda()
File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in cuda
    return self._apply(lambda t: t.cuda(device))
File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in <lambda>
    return self._apply(lambda t: t.cuda(device))
![image](https://user-images.githubusercontent.com/4637296/119266000-a8e4a000-bbf1-11eb-9d83-baa7c0ba097c.png)

**Comment by jxust01** [comment]
me too

**Comment by jxust01** [comment]
> Hi,
> I running streamlit run app.py on the WebUI branch on AWS p3.16xlarge server with the following setup
> GPU 8,
> GPU peer to Peer NVLink
> GPU memory (GB) 128
> vCPU 64
> Memory (GP) 488
> Cuda compilation tools, release 10.0, V10.0.130
> 
> getting the error RuntimeError: CUDA error: out of memory
> 
> File "/home/ubuntu/.local/lib/python3.6/site-packages/streamlit/script_runner.py", line 338, in _run_script
> exec(code, module.**dict**)
> File "/home/ubuntu/src/StyleFlow/webui/app.py", line 312, in
> main()
> File "/home/ubuntu/src/StyleFlow/webui/app.py", line 219, in main
> session, model, w_avg, flow_model = init_model()
> File "/home/ubuntu/.local/lib/python3.6/site-packages/streamlit/caching.py", line 573, in wrapped_func
> return get_or_create_cached_value()
> File "/home/ubuntu/.local/lib/python3.6/site-packages/streamlit/caching.py", line 557, in get_or_create_cached_value
> return_value = func(*args, **kwargs)
> File "/home/ubuntu/src/StyleFlow/webui/app.py", line 104, in init_model
> prior = cnf(512, '512-512-512-512-512', 17, 1)
> File "../module/flow.py", line 79, in cnf
> model = build_model(input_dim, dims, zdim, num_blocks, True).cuda()
> File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in cuda
> return self._apply(lambda t: t.cuda(device))
> File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 387, in _apply
> module._apply(fn)
> File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 387, in _apply
> module._apply(fn)
> File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 409, in _apply
> param_applied = fn(param)
> File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in
> return self._apply(lambda t: t.cuda(device))
> ![image](https://user-images.githubusercontent.com/4637296/119266000-a8e4a000-bbf1-11eb-9d83-baa7c0ba097c.png)
> 
> Any assistance would be appreciated
> Rony

I solved this problemjust now

**Comment by jxust01** [comment]
> Hi,
> I running streamlit run app.py on the WebUI branch on AWS p3.16xlarge server with the following setup
> GPU 8,
> GPU peer to Peer NVLink
> GPU memory (GB) 128
> vCPU 64
> Memory (GP) 488
> Cuda compilation tools, release 10.0, V10.0.130
> 
> getting the error RuntimeError: CUDA error: out of memory
> 
> File "/home/ubuntu/.local/lib/python3.6/site-packages/streamlit/script_runner.py", line 338, in _run_script
> exec(code, module.**dict**)
> File "/home/ubuntu/src/StyleFlow/webui/app.py", line 312, in
> main()
> File "/home/ubuntu/src/StyleFlow/webui/app.py", line 219, in main
> session, model, w_avg, flow_model = init_model()
> File "/home/ubuntu/.local/lib/python3.6/site-packages/streamlit/caching.py", line 573, in wrapped_func
> return get_or_create_cached_value()
> File "/home/ubuntu/.local/lib/python3.6/site-packages/streamlit/caching.py", line 557, in get_or_create_cached_value
> return_value = func(*args, **kwargs)
> File "/home/ubuntu/src/StyleFlow/webui/app.py", line 104, in init_model
> prior = cnf(512, '512-512-512-512-512', 17, 1)
> File "../module/flow.py", line 79, in cnf
> model = build_model(input_dim, dims, zdim, num_blocks, True).cuda()
> File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in cuda
> return self._apply(lambda t: t.cuda(device))
> File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 387, in _apply
> module._apply(fn)
> File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 387, in _apply
> module._apply(fn)
> File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 409, in _apply
> param_applied = fn(param)
> File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in
> return self._apply(lambda t: t.cuda(device))
> ![image](https://user-images.githubusercontent.com/4637296/119266000-a8e4a000-bbf1-11eb-9d83-baa7c0ba097c.png)
> 
> Any assistance would be appreciated
> Rony

![image](https://user-images.githubusercontent.com/35182265/124744456-5bc64e80-df51-11eb-8a9a-7e292a1b2098.png)

**Comment by jxust01** [comment]
@st.cache(hash_funcs=HASH_FUNCS)
def init_model():
    # Open a new TensorFlow session.
    gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.2)  # Set GPU resource occupancy ratio
    config = tf.ConfigProto(allow_soft_placement=True, gpu_options=gpu_options)
    session = tf.Session(config=config)

And some other minor modifications（cpu -> cuda、slider、etc...）

**Comment by lijiae** [comment]
> @st.cache(hash_funcs=HASH_FUNCS)
> def init_model():
> # Open a new TensorFlow session.
> gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.2) # Set GPU resource occupancy ratio
> config = tf.ConfigProto(allow_soft_placement=True, gpu_options=gpu_options)
> session = tf.Session(config=config)
> 
> And some other minor modifications（cpu -> cuda、slider、etc...）

it works!!!! tks a lot

**Comment by xgy2000** [comment]
![image](https://user-images.githubusercontent.com/13026673/127311325-52f53764-891c-4824-9df1-4da5915167a4.png)

**Comment by vaan2010** [comment]
@xgy2000 you can modify the code at /usr/local/lib/python3.7/dist-packages/streamlit/state/widgets.py line 132, 
change 
element_proto.id = widget_id
to 
element_proto.id = str(widget_id)

it works for me!

**Comment by zhywanna** [comment]
> Hi, I running streamlit run app.py on the WebUI branch on AWS p3.16xlarge server with the following setup GPU 8, GPU peer to Peer NVLink GPU memory (GB) 128 vCPU 64 Memory (GP) 488 Cuda compilation tools, release 10.0, V10.0.130
> 
> getting the error RuntimeError: CUDA error: out of memory
> 
> File "/home/ubuntu/.local/lib/python3.6/site-packages/streamlit/script_runner.py", line 338, in _run_script exec(code, module.**dict**) File "/home/ubuntu/src/StyleFlow/webui/app.py", line 312, in main() File "/home/ubuntu/src/StyleFlow/webui/app.py", line 219, in main session, model, w_avg, flow_model = init_model() File "/home/ubuntu/.local/lib/python3.6/site-packages/streamlit/caching.py", line 573, in wrapped_func return get_or_create_cached_value() File "/home/ubuntu/.local/lib/python3.6/site-packages/streamlit/caching.py", line 557, in get_or_create_cached_value return_value = func(*args, **kwargs) File "/home/ubuntu/src/StyleFlow/webui/app.py", line 104, in init_model prior = cnf(512, '512-512-512-512-512', 17, 1) File "../module/flow.py", line 79, in cnf model = build_model(input_dim, dims, zdim, num_blocks, True).cuda() File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in cuda return self._apply(lambda t: t.cuda(device)) File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 387, in _apply module._apply(fn) File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 387, in _apply module._apply(fn) File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 409, in _apply param_applied = fn(param) File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in return self._apply(lambda t: t.cuda(device)) ![image](https://user-images.githubusercontent.com/4637296/119266000-a8e4a000-bbf1-11eb-9d83-baa7c0ba097c.png)
> 
> Any assistance would be appreciated Rony

UnpicklingError: pickle data was truncated
![image](https://user-images.githubusercontent.com/47680024/187414847-14d8bfe5-04fa-4b9d-aaea-089061a00be6.png)
